### ISSUE TITLE
Review readme

### ISSUE THREAD

**Issue by jonasaragao** [AlexandreBonfim/meetup-api#1]
Tentei instalar o app aqui no meu PC e não fui muito bem sucedido. 
Abri uma branch pra melhorar os passos

Travei especificamente na database
![Screenshot 2019-04-24 at 08 06 17](https://user-images.githubusercontent.com/9805112/56639149-e750af00-6667-11e9-9764-faf5f3e6021c.png)

User aquele username e password do readme, mas não rolou. Esse é o meu .env no momento:
![image](https://user-images.githubusercontent.com/9805112/56639259-27b02d00-6668-11e9-81c0-f7a6678a2c1b.png)

**Comment by AlexandreBonfim** [comment]
ENV: 

HOST=127.0.0.1
PORT=3333
NODE_ENV=development
APP_NAME=AdonisJs
APP_URL=http://${HOST}:${PORT}
CACHE_VIEWS=false
APP_KEY=uuhxEey5LKSkxRKE7uA7rS07CjeaHD1p

DB_CONNECTION=pg
DB_HOST=127.0.0.1
DB_PORT=5432
DB_USER=docker
DB_PASSWORD=docker
DB_DATABASE=meetup

HASH_DRIVER=bcrypt

MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=e2375ffc6bf15b
MAIL_PASSWORD=30fff61f2c5818
